
my:
  greeting: Hello World Default-------

app:
  description: Welcome Active to ${app.name}
  data.lst: 1,2,3,4
  jsondata: "{key1:'value1',key2:'value2'}"

db:
  connection: connectionstringurl
  username: spring
  password: tiger

 
management.endpoints.web.exposure.include: "*"

spring.cloud.config.uri: http://localhost:8888
spring:  profiles:    active: default